---
- name: Install base development tools
  community.general.pacman:
    name:
      - linux-headers
      - base-devel
      - git
      - less
    state: present
    become: true

- name: Install env utilities
  community.general.pacman:
    name:
      - bash-completion
      - chezmoi
    state: present
    become: true

- name: Install camera packages
  community.general.pacman:
    name:
      - pipewire-libcamera
      - libcamera-tools
    state: present
    become: true

- name: Install network packages
  community.general.pacman:
    name:
      - networkmanager-openvpn
    state: present
    become: true

- name: Install desktop integration packages
  community.general.pacman:
    name:
      - xdg-desktop-portal-gnome
    state: present
    become: true

- name: Install Docker packages
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present
    become: true

- name: Install Kubernetes packages
  community.general.pacman:
    name:
      - kubectl
      - helm
    state: present
    become: true

- name: Install AWS CLI packages
  community.general.pacman:
    name:
      - aws-cli-v2
    state: present
    become: true

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
