---
- name: Install secure boot utilities
  community.general.pacman:
    name:
      - sbctl
    state: present
    become: true

- name: Check sbctl status
  ansible.builtin.command: sbctl status
  register: sbctl_status
  changed_when: false
  failed_when: false

- name: Create secure boot keys
  ansible.builtin.command: sbctl create-keys
  when: "sbctl_status.stdout is not search('Installed:.*✓')"
  become: true

- name: Sign EFI binaries
  ansible.builtin.command: "sbctl sign -s {{ item }}"
  loop:
    - /boot/EFI/BOOT/BOOTX64.EFI
    - /boot/vmlinuz-linux
    - /boot/EFI/systemd/systemd-bootx64.efi
    - /boot/EFI/Linux/arch-linux.efi
  changed_when: true

- name: Verify signed EFI binaries
  ansible.builtin.command: sbctl verify
  register: sbctl_verify
  changed_when: false
  become: true

- name: Remove immutable attribute from EFI variables
  ansible.builtin.shell: |
    for f in /sys/firmware/efi/efivars/{KEK,db}-*; do
        if [ -f "$f" ]; then
            chattr -i "$f"
        fi
    done
  args:
    executable: /bin/bash
  when: "sbctl_status.stdout is search('Enrolled:.*✘')"
  changed_when: true
  become: true

- name: Enroll secure boot keys
  ansible.builtin.command: "sbctl enroll-keys -m"
  register: enroll_result
  when:
    - "sbctl_status.stdout is search('Enrolled:.*✘')"
    - "sbctl_status.stdout is search('Setup Mode:.*Enabled')"
  become: true

- name: Reboot local machine (Fire and Forget)
  ansible.builtin.shell: "sleep 2 && shutdown -r now"
  async: 1
  poll: 0
  when: enroll_result is changed
  become: true

- name: Stop playbook execution
  ansible.builtin.meta: end_play
  when: enroll_result is changed
