---
- name: Install flatpak
  become: true
  community.general.pacman:
    name: flatpak
    state: present
    update_cache: true

- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    method: user
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak applications
  loop: "{{ flatpak_apps }}"
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
    remote: flathub
