---
- name: Install docker binaries
  become: true
  community.general.pacman:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: true

- name: Check if /var/lib/docker is on Btrfs
  ansible.builtin.set_fact:
    docker_is_btrfs: "{{ docker_is_btrfs | default(false) or item.fstype == 'btrfs' }}"
  loop: "{{ ansible_facts['mounts'] }}"
  when: item.mount in ['/', '/var/lib/docker']

- name: Configure Docker daemon (JSON)
  become: true
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: "0644"
    content: |
      {
        "storage-driver": "{{ 'btrfs' if docker_is_btrfs | default(false) else 'overlay2' }}"
      }
  notify: Restart docker

- name: Enable and start Docker service
  become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
